//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournament_422_Nazarycheva.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Player()
        {
            this.ResultPlayer = new HashSet<ResultPlayer>();
            this.StageRestriction = new HashSet<StageRestriction>();
        }
    
        public int Id { get; set; }
        public Nullable<int> TeamId { get; set; }
        public string Nickname { get; set; }
        public string Phone { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<int> RegionId { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
    
        public virtual Region Region { get; set; }
        public virtual Role Role { get; set; }
        public virtual Team Team { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResultPlayer> ResultPlayer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StageRestriction> StageRestriction { get; set; }
    }
}
