//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournament_422_Nazarycheva.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultPlayer
    {
        public int Id { get; set; }
        public Nullable<int> PlayerId { get; set; }
        public Nullable<int> TournamentId { get; set; }
        public Nullable<int> Points { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual Tournament Tournament { get; set; }
    }
}
